name: 🔍 Debug CD Trigger

on:
  workflow_run:
    workflows: ["CI Pipeline (unit + e2e)"]  # Must match the CI workflow's name exactly
    types:
      - completed

jobs:
  debug:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Print event info
        run: |
          echo "✅ CI pipeline completed successfully"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Commit SHA: ${{ github.event.workflow_run.head_sha }}"
          echo "Conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Triggered by workflow: ${{ github.event.workflow_run.name }}"
